name: Fetch DSO Configs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  push:
    branches:
      - stas/actions_fetch_dso_configs_regularily

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  fetch-configs-and-create-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch DSO configs
        id: fetch-dso-configs
        run: scripts/fetch-dso-configs.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e  # v7.0.8
        with:
          commit-message: |
            "Update DSO configs"

            ${{ steps.fetch-dso-configs.outputs.pr_body }}
          title: "Update DSO configs"
          body: ${{ steps.fetch-dso-configs.outputs.pr_body }}
