name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Default is 1. We set it as 0 to get access to the target branch

      - name: Validate JSON and YAML files
        uses: GrantBirki/json-yaml-validate@e42e6ece9b97f2b220274c909a9a98e380c2c9fd  # v3.2.1
        with:
          base_dir: configs
          use_gitignore: false

      - name: Check SV IDs for duplicates
        run: |
          result=$(scripts/check-sv-id-dups.sh) && exit_code=$? || exit_code=$?
          echo "$result"

          {
            echo '```'
            echo "$result"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

          exit "$exit_code"
        env:
          SV_IDS_EXCLUDE: |
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsRRntNkOLF2Wh7JxV0rBQPgT+SendIjFLXKUXCrLbVHqomkypHQiZP8OgFMSlByOnr81fqiUt3G36LUpg/fmgA==  # TODO: Remove this when one of DevNet/Digital-Asset-Eng-2 or TestNet/Digital-Asset-1 gets a new ID

      - name: Make sure total sum of reward weights doesn't change unless explicitly allowed
        run: |
          result=$(scripts/check-sum-reward-weights-change.sh "$TARGET_BRANCH" "$SOURCE_BRANCH") && exit_code=$? || exit_code=$?
          echo "$result"

          {
            echo '```'
            echo "$result"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

          exit "$exit_code"
        env:
          SOURCE_BRANCH: ${{ github.event.pull_request.head.sha }}
          TARGET_BRANCH: "origin/${{ github.base_ref }}"
